output_dir: ./models/full_ft
overwrite_output_dir: true
do_train: true
do_eval: true
evaluation_strategy: steps
eval_steps: 100
num_train_epochs: 3
per_device_train_batch_size: 46
per_device_eval_batch_size: 82
learning_rate: 5e-5
logging_strategy: steps
logging_steps: 10
save_strategy: steps
save_total_limit: 1
bf16: true
dataloader_num_workers: 4
load_best_model_at_end: true
report_to: mlflow
remove_unused_columns: false