output_dir: ./models/LORA_ft
overwrite_output_dir: true
do_train: true
do_eval: true
evaluation_strategy: steps
eval_steps: 50
num_train_epochs: 3
per_device_train_batch_size: 64
per_device_eval_batch_size: 64
learning_rate: 5e-5
logging_strategy: steps
logging_steps: 5
save_strategy: steps
save_total_limit: 1
bf16: true
dataloader_num_workers: 4
load_best_model_at_end: true
report_to: mlflow
remove_unused_columns: false
label_names: 
  - labels